// <auto-generated />
namespace Soft.WebApi.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Adicionando_tabelas_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicionando_tabelas_users));
        
        string IMigrationMetadata.Id
        {
            get { return "202103160100346_Adicionando_tabelas_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
